import type { Book, Loan, User, StudyRoom, AcademicEvent, DigitalResource } from './types';

// ── Libros mock ampliados ──────────────────
export const INITIAL_BOOKS: Book[] = [
    {
        id: "b1",
        isbn: "978-0141187761",
        title: "1984",
        author: "George Orwell",
        description: "Una novela distópica clásica sobre vigilancia gubernamental y control totalitario.",
        category: "Ficción",
        faculty: "Humanidades",
        image: "https://placehold.co/800x600/1a237e/ffffff?text=1984",
        totalStock: 5,
        availableCopies: 3,
        status: 'available',
        isFeatured: true,
    },
    {
        id: "b2",
        isbn: "978-0307474728",
        title: "Cien Años de Soledad",
        author: "Gabriel García Márquez",
        description: "La obra maestra del realismo mágico que narra la historia de la familia Buendía en Macondo.",
        category: "Literatura Latina",
        faculty: "Humanidades",
        image: "https://placehold.co/800x600/c9a84c/1a237e?text=Cien+Años",
        totalStock: 8,
        availableCopies: 8,
        status: 'available',
        isFeatured: true,
    },
    {
        id: "b3",
        isbn: "978-0618260300",
        title: "El Señor de los Anillos",
        author: "J.R.R. Tolkien",
        description: "El comienzo de la épica aventura para destruir el Anillo Único.",
        category: "Fantasía",
        faculty: "Humanidades",
        image: "https://placehold.co/800x600/00796b/ffffff?text=LOTR",
        totalStock: 4,
        availableCopies: 0,
        status: 'out_of_stock',
        isFeatured: false,
    },
    {
        id: "b4",
        isbn: "978-0131103627",
        title: "The C Programming Language",
        author: "Kernighan & Ritchie",
        description: "La biblia del lenguaje C para programadores y entusiastas del software.",
        category: "Programación",
        faculty: "Ingeniería",
        image: "https://placehold.co/800x600/263238/4fc3f7?text=C+Lang",
        totalStock: 3,
        availableCopies: 2,
        status: 'available',
        isFeatured: false,
    },
    {
        id: "b5",
        isbn: "978-1501142970",
        title: "Cálculo de una Variable",
        author: "James Stewart",
        description: "Texto fundamental de cálculo diferencial e integral para estudiantes de ingeniería y ciencias.",
        category: "Matemáticas",
        faculty: "Ciencias",
        image: "https://placehold.co/800x600/1565c0/ffffff?text=Cálculo",
        totalStock: 12,
        availableCopies: 4,
        status: 'available',
        isFeatured: true,
    },
    {
        id: "b6",
        isbn: "978-0321774187",
        title: "Principios de Anatomía y Fisiología",
        author: "Gerard Tortora",
        description: "Referencia esencial para estudiantes de medicina y ciencias de la salud con ilustraciones detalladas.",
        category: "Medicina",
        faculty: "Medicina",
        image: "https://placehold.co/800x600/c62828/ffffff?text=Anatomía",
        totalStock: 6,
        availableCopies: 1,
        status: 'low_stock',
        isFeatured: true,
    },
    {
        id: "b7",
        isbn: "978-6071512123",
        title: "Derecho Constitucional",
        author: "Ignacio Burgoa",
        description: "Análisis integral de las garantías constitucionales y la estructura del Estado.",
        category: "Derecho",
        faculty: "Derecho",
        image: "https://placehold.co/800x600/4a148c/ffffff?text=Derecho",
        totalStock: 7,
        availableCopies: 5,
        status: 'available',
        isFeatured: false,
    },
    {
        id: "b8",
        isbn: "978-0134685991",
        title: "Effective Java",
        author: "Joshua Bloch",
        description: "Guía definitiva de mejores prácticas para el desarrollo de software en Java.",
        category: "Programación",
        faculty: "Ingeniería",
        image: "https://placehold.co/800x600/1b5e20/ffffff?text=Java",
        totalStock: 5,
        availableCopies: 3,
        status: 'available',
        isFeatured: false,
    },
    {
        id: "b9",
        isbn: "978-0136042594",
        title: "Física Universitaria Vol.1",
        author: "Sears & Zemansky",
        description: "Texto clásico de física para ingeniería con problemas resueltos y análisis conceptual.",
        category: "Física",
        faculty: "Ciencias",
        image: "https://placehold.co/800x600/0d47a1/ffffff?text=Física",
        totalStock: 10,
        availableCopies: 6,
        status: 'available',
        isFeatured: true,
    },
    {
        id: "b10",
        isbn: "978-8490354650",
        title: "Psicología Social",
        author: "David Myers",
        description: "Exploración completa de la influencia social, percepción y comportamiento humano en grupo.",
        category: "Psicología",
        faculty: "Humanidades",
        image: "https://placehold.co/800x600/6a1b9a/ffffff?text=Psicología",
        totalStock: 4,
        availableCopies: 2,
        status: 'available',
        isFeatured: false,
    },
    {
        id: "b11",
        isbn: "978-0073398068",
        title: "Microeconomía",
        author: "Michael Parkin",
        description: "Principios microeconómicos con aplicaciones al mundo real y análisis de mercados.",
        category: "Economía",
        faculty: "Economía",
        image: "https://placehold.co/800x600/e65100/ffffff?text=Micro",
        totalStock: 6,
        availableCopies: 0,
        status: 'out_of_stock',
        isFeatured: false,
    },
    {
        id: "b12",
        isbn: "978-0321696366",
        title: "Química Orgánica",
        author: "L.G. Wade Jr.",
        description: "Texto integral de química orgánica con mecanismos de reacción y síntesis.",
        category: "Química",
        faculty: "Ciencias",
        image: "https://placehold.co/800x600/00695c/ffffff?text=Química",
        totalStock: 5,
        availableCopies: 3,
        status: 'available',
        isFeatured: false,
    },
];

// Usuarios mock
export const MOCK_USERS: User[] = [
    { id: "u1", name: "Valentina Soto", email: "v.soto@u.edu", role: "student", idNumber: "2023001", faculty: "Ingeniería", semester: 5 },
    { id: "u2", name: "Carlos Ruiz", email: "c.ruiz@u.edu", role: "librarian", idNumber: "L-501" },
    { id: "u3", name: "Admin General", email: "admin@u.edu", role: "admin", idNumber: "A-001" },
    { id: "u4", name: "Mariana López", email: "m.lopez@u.edu", role: "student", idNumber: "2023042", faculty: "Medicina", semester: 3 },
    { id: "u5", name: "Diego Fernández", email: "d.fernandez@u.edu", role: "student", idNumber: "2022118", faculty: "Derecho", semester: 7 },
    { id: "u6", name: "Camila Torres", email: "c.torres@u.edu", role: "student", idNumber: "2024005", faculty: "Ciencias", semester: 2 },
];

// Préstamos mock
export const MOCK_LOANS: Loan[] = [
    {
        id: "L-001",
        userId: "u1",
        userName: "Valentina Soto",
        bookId: "b3",
        bookTitle: "El Señor de los Anillos",
        startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        status: "active",
    },
    {
        id: "L-002",
        userId: "u1",
        userName: "Valentina Soto",
        bookId: "b1",
        bookTitle: "1984",
        startDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        status: "overdue",
        penalty: 2500,
    },
    {
        id: "L-003",
        userId: "u2",
        userName: "Carlos Ruiz",
        bookId: "b2",
        bookTitle: "Cien Años de Soledad",
        startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
        returnDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        status: "returned",
    },
    {
        id: "L-004",
        userId: "u4",
        userName: "Mariana López",
        bookId: "b6",
        bookTitle: "Principios de Anatomía y Fisiología",
        startDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
        status: "active",
    },
    {
        id: "L-005",
        userId: "u5",
        userName: "Diego Fernández",
        bookId: "b7",
        bookTitle: "Derecho Constitucional",
        startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        status: "active",
    },
];

// Salas de estudio
export const MOCK_STUDY_ROOMS: StudyRoom[] = [
    { id: "sr1", name: "Sala Neruda", capacity: 8, floor: 1, equipment: ["Proyector", "Pizarra"], available: true },
    { id: "sr2", name: "Sala Mistral", capacity: 4, floor: 1, equipment: ["Monitor TV"], available: false, currentUser: "Grupo Cálculo III", nextAvailable: "16:00" },
    { id: "sr3", name: "Sala Borges", capacity: 12, floor: 2, equipment: ["Proyector", "Audio", "Pizarra"], available: true },
    { id: "sr4", name: "Sala Cortázar", capacity: 6, floor: 2, equipment: ["Pizarra", "Monitor TV"], available: false, currentUser: "Seminario Derecho", nextAvailable: "18:30" },
    { id: "sr5", name: "Sala Allende", capacity: 20, floor: 3, equipment: ["Proyector", "Audio", "Videoconferencia"], available: true },
    { id: "sr6", name: "Cubículo Individual 1", capacity: 1, floor: 1, equipment: ["Enchufe", "Lámpara"], available: true },
    { id: "sr7", name: "Cubículo Individual 2", capacity: 1, floor: 1, equipment: ["Enchufe", "Lámpara"], available: false, currentUser: "Diego F.", nextAvailable: "15:00" },
];

// Eventos académicos
export const MOCK_EVENTS: AcademicEvent[] = [
    { id: "e1", title: "Taller: Búsqueda en Bases de Datos", description: "Aprende a usar EBSCO, Scopus y Web of Science para tu investigación.", date: "2026-04-02", time: "10:00", location: "Sala Multimedia, Piso 2", type: "workshop", speaker: "Bib. María Gutiérrez" },
    { id: "e2", title: "Seminario: Inteligencia Artificial en la Educación", description: "Exploración del impacto de IA generativa en la formación universitaria.", date: "2026-04-05", time: "15:00", location: "Auditorio Central", type: "seminar", speaker: "Dr. Alejandro Vega" },
    { id: "e3", title: "Expo: Feria del Libro Universitario", description: "Exposición anual con editoriales académicas y descuentos exclusivos.", date: "2026-04-10", time: "09:00", location: "Hall Principal", type: "expo" },
    { id: "e4", title: "Conferencia: Derechos Digitales y Privacidad", description: "Marco legal sobre protección de datos personales en la era digital.", date: "2026-04-15", time: "11:00", location: "Sala Borges, Piso 2", type: "conference", speaker: "Dra. Paulina Reyes" },
];

// Recursos digitales
export const MOCK_DIGITAL_RESOURCES: DigitalResource[] = [
    { id: "dr1", name: "EBSCO Academic Search", type: "database", description: "Acceso a miles de artículos académicos revisados por pares.", url: "#", accessLevel: "institutional", icon: "🔬" },
    { id: "dr2", name: "Scopus", type: "database", description: "Base de datos de citas y resúmenes de literatura científica.", url: "#", accessLevel: "institutional", icon: "📊" },
    { id: "dr3", name: "SciELO", type: "journal", description: "Biblioteca electrónica de revistas científicas latinoamericanas.", url: "#", accessLevel: "open", icon: "📰" },
    { id: "dr4", name: "Repositorio Institucional", type: "repository", description: "Tesis, memorias y publicaciones de nuestra universidad.", url: "#", accessLevel: "open", icon: "🎓" },
    { id: "dr5", name: "SpringerLink eBooks", type: "ebook", description: "Colección de libros electrónicos en ciencia, tecnología y medicina.", url: "#", accessLevel: "institutional", icon: "📚" },
    { id: "dr6", name: "IEEE Xplore", type: "database", description: "Publicaciones en ingeniería eléctrica, computación y electrónica.", url: "#", accessLevel: "institutional", icon: "⚡" },
];
